version: 0.0
os: ubiuntu
files:
  - source: /
    destination: /backend
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: ubuntu
      commands:
        - echo "Executing BeforeInstall steps..."
        - pip install gunicorn
  AfterInstall:
    - location: scripts/install_dependencies.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: ubuntu
  ValidateService:
    - location: scripts/validate_service.sh
      runas: ubuntu
