version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      # Install dependencies
      - pip install -r ./backend/requirements.txt

  pre_build:
    commands:
      # Collect static files
      - cd backend/myproject
      - ls

  build:
    commands:
      # Run migrations
      - ls
      - cd backend/myproject
      - python manage.py migrate

artifacts:
  files:
    - '**/*'
